### ISSUE TITLE
Using datetimePicker inside fragment

### ISSUE THREAD

**Issue by demo-Ashif** [CiTuX/datetimepicker#14]
inside of a Button onClick method I write -

DatePickerDialog.newInstance(this, calendar2.get(Calendar.YEAR), calendar2.get(Calendar.MONTH), calendar2.get(Calendar.DAY_OF_MONTH)).show(getFragmentManager(), "datePicker");

but its causing error - 'wrong 1st argument type. Found android.view.View.OnClickListener, required com.android.datetimepicker.date.DatePickerDialog.OnDateSetListener' 

How to solve this ???

**Comment by CiTuX** [comment]
The exception describes the problem very well.
You're creating the `DatePickerDialog` inside the onClick method, which is why `this` points to a `View.OnClickListener`.

There are two solutions for this problem:

* Instead of passing this, you can pass [fragmentname].this (for example `MyFragment.this`)
```java
DatePickerDialog.newInstance(
        MyFragment.this,
        calendar2.get(Calendar.YEAR),
        calendar2.get(Calendar.MONTH),
        calendar2.get(Calendar.DAY_OF_MONTH)
).show(getFragmentManager(), "datePicker");
```
* Create an anonymous `OnDateSetListener`
```java
DatePickerDialog.newInstance(
        new DatePickerDialog.OnDateSetListener() {
            @Override
            public void onDateSet(DatePickerDialog dialog, int year, int monthOfYear, int dayOfMonth) {
                //User selected date
            }
        },
        calendar2.get(Calendar.YEAR),
        calendar2.get(Calendar.MONTH),
        calendar2.get(Calendar.DAY_OF_MONTH)
).show(getFragmentManager(), "datePicker");
```

You can also take a look at the demo app.

**Comment by RajeshNaddy** [comment]
Dob.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                // TODO Auto-generated method stub
                
                DatePickerDialog.newInstance(new DatePickerDialog.OnDateSetListener() {
                    @Override
                    public void onDateSet(DatePickerDialog dialog, int year, int monthOfYear, int dayOfMonth) {
                        //User selected date
                    }
                }, calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH), calendar.get(Calendar.DAY_OF_MONTH)).show(getActivity().getFragmentManager(), "datePicker");
            }
        });
