### ISSUE TITLE
Outdated support version required

### ISSUE THREAD

**Issue by C-Otto** [CiTuX/datetimepicker#20]
In https://github.com/CiTuX/datetimepicker/blob/master/library/build.gradle#L19 an outdated version of the support library is included. This causes problems as I am unable (and unwilling) to install it.

**Comment by C-Otto** [comment]
@CiTuX Could you use the "+" notation? Otherwise this issue will pop up again in a short while.

**Comment by CiTuX** [comment]
Sorry, I don't know wich notation you mean. What does the "+"?

**Comment by C-Otto** [comment]
You could write something like `compile 'com.android.support:support-v13:23+'`. However, Google advises against using dynamic version numbers:

```
Caution: Using dynamic dependencies, especially for higher version numbers, can cause unexpected version updates and regression incompatibilities.
```

Sadly, I don't know about the details, the regression issues, or the meaning of this package and its versions. As long as the library can be used - which currently does not work as indicated in the initial report - I'm happy. Could you provide a new release after deciding on a fix?

**Comment by C-Otto** [comment]
I fixed this by installing/updating more of the SDK options. Sorry for the confusion, this bug was invalid from the start.
