### ISSUE TITLE
java.lang.ClassCastException: com.appeaser.sublimepickerlibrary.datepicker.PickerViewAnimator cannot be cast to com.android.datetimepicker.date.AccessibleDateAnimator

### ISSUE THREAD

**Issue by polaris0227** [CiTuX/datetimepicker#23]
java.lang.ClassCastException: com.appeaser.sublimepickerlibrary.datepicker.PickerViewAnimator cannot be cast to com.android.datetimepicker.date.AccessibleDateAnimator

Please provide solution if you resolve it.
Many thanks.

**Comment by sureshkumarm8** [comment]
I have same problem in my project... cannot be cast to com.android.datetimepicker.date.AccessibleDateAnimator
