### ISSUE TITLE
Color Change

### ISSUE THREAD

**Issue by Vibinreji** [CiTuX/datetimepicker#29]
Can i change programmatically color of the selected date and month colors.In default it is blue i need to change based on my app primary color.

**Comment by CiTuX** [comment]
Yes, it's possible.
You just have to override the `blue` color in your `colors.xml` like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="blue">#972343</color>
</resources>
```
You can find all colors [here](https://android.googlesource.com/platform/frameworks/opt/datetimepicker/+/master/res/values/colors.xml).

**Comment by Vibinreji** [comment]
Got it.Thanks

**Comment by CiTuX** [comment]
👍
