### ISSUE TITLE
it is possible to change the font color?

### ISSUE THREAD

**Issue by Wyllyam** [CiTuX/datetimepicker#4]
iked the project, however wanted to change the font color of the blue the red

**Comment by devKemo** [comment]
you can simply override the library colors by using the same name attribute of the colors used in the library in your res/values/colors.xml and giving it new values.
here is a list of the all colors used in the library:

    <color name="white">#ffffff</color>
    <color name="circle_background">#f2f2f2</color>
    <color name="line_background">#cccccc</color>
    <color name="ampm_text_color">#8c8c8c</color>
    <color name="done_text_color_normal">#000000</color>
    <color name="done_text_color_disabled">#cccccc</color>
    <color name="numbers_text_color">#8c8c8c</color>

    <color name="transparent_black">#7f000000</color>
    <color name="blue">#33b5e5</color>
    <color name="blue_focused">#c1e8f7</color>
    <color name="neutral_pressed">#33999999</color>
    <color name="darker_blue">#0099cc</color>
    <color name="date_picker_text_normal">#ff999999</color>
    <color name="date_picker_text_disabled">#ccc</color>

    <color name="calendar_header">#999999</color>
    <color name="date_picker_view_animator">#f2f2f2</color>
    <color name="calendar_selected_date_text">#ffd1d2d4</color>

    
    <color name="red">#ff3333</color>
    <color name="red_focused">#853333</color>
    <color name="light_gray">#404040</color>
    <color name="dark_gray">#363636</color>
    <color name="line_dark">#808080</color>
    <color name="done_text_color_dark_normal">#ffffff</color>
    <color name="done_text_color_dark_disabled">#888888</color>
    <color name="done_disabled_dark">#bfbfbf</color>
