### ISSUE TITLE
getTag() problem

### ISSUE THREAD

**Issue by raplider** [CiTuX/datetimepicker#6]
in public void onTimeSet(RadialPickerLayout radialPickerLayout, int hourOfDay, int minute)

radialPickerLayout.getTag() every time return null

**Comment by gersonmendes** [comment]
I face this problem when work with multiple pickers in the same fragment. I build this workaround:

if(getActivity().getFragmentManager().findFragmentByTag("start") != null){
            mStartEditText.setText(mFormatTime.format(mCalendar.getTime()));
        }else if(getActivity().getFragmentManager().findFragmentByTag("end") != null){
            mEndEditText.setText(mFormatTime.format(mCalendar.getTime()));
        }

**Comment by jensbrulmans** [comment]
Thank you @gersonmendes !
